name: scheduler_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/fonts/Noto_Sans_SC/

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/Noto_Sans_SC/static/NotoSansSC-Regular.ttf
        - asset: assets/fonts/Noto_Sans_SC/static/NotoSansSC-Bold.ttf
          weight: 700
